spring:
  application:
    name: "workouts"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:liamo}"
    username: "${DB_USERNAME:liamo}"
    password: "${DB_PASSWORD:db_pass}"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
